package com.bawei.week2_practice.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.week2_practice.entity.GreenDaoCacheBean;

import com.bawei.week2_practice.greendao.GreenDaoCacheBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoCacheBeanDaoConfig;

    private final GreenDaoCacheBeanDao greenDaoCacheBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoCacheBeanDaoConfig = daoConfigMap.get(GreenDaoCacheBeanDao.class).clone();
        greenDaoCacheBeanDaoConfig.initIdentityScope(type);

        greenDaoCacheBeanDao = new GreenDaoCacheBeanDao(greenDaoCacheBeanDaoConfig, this);

        registerDao(GreenDaoCacheBean.class, greenDaoCacheBeanDao);
    }
    
    public void clear() {
        greenDaoCacheBeanDaoConfig.clearIdentityScope();
    }

    public GreenDaoCacheBeanDao getGreenDaoCacheBeanDao() {
        return greenDaoCacheBeanDao;
    }

}
