package com.bawei.week2_practice.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.week2_practice.entity.GreenDaoCacheBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_DAO_CACHE_BEAN".
*/
public class GreenDaoCacheBeanDao extends AbstractDao<GreenDaoCacheBean, Void> {

    public static final String TABLENAME = "GREEN_DAO_CACHE_BEAN";

    /**
     * Properties of entity GreenDaoCacheBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Json = new Property(0, String.class, "json", false, "JSON");
    }


    public GreenDaoCacheBeanDao(DaoConfig config) {
        super(config);
    }
    
    public GreenDaoCacheBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_DAO_CACHE_BEAN\" (" + //
                "\"JSON\" TEXT);"); // 0: json
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_DAO_CACHE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GreenDaoCacheBean entity) {
        stmt.clearBindings();
 
        String json = entity.getJson();
        if (json != null) {
            stmt.bindString(1, json);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GreenDaoCacheBean entity) {
        stmt.clearBindings();
 
        String json = entity.getJson();
        if (json != null) {
            stmt.bindString(1, json);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public GreenDaoCacheBean readEntity(Cursor cursor, int offset) {
        GreenDaoCacheBean entity = new GreenDaoCacheBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // json
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GreenDaoCacheBean entity, int offset) {
        entity.setJson(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(GreenDaoCacheBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(GreenDaoCacheBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(GreenDaoCacheBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
